import messages from '../../../messages/en.json'
import { defaultLocale, type Locale } from './config'

/**
 * The dictionary is keyed on the Norwegian source string, not on invented keys.
 *
 * That mirrors how Weglot's own translation memory is keyed, so a correction
 * made in the Weglot dashboard lines up 1:1 with what the code asks for. It
 * also means an untranslated string degrades to Norwegian rather than to a
 * missing-key placeholder.
 *
 * Generated by scripts/translate.ts and committed, so rendering never touches
 * the network.
 */
const dictionaries: Record<Locale, Record<string, string>> = {
  nb: {},
  en: messages as Record<string, string>,
}

export type Translate = (source: string) => string

/**
 * Normalises the whitespace that JSX introduces, so a string broken across
 * source lines still matches the single-line key Weglot was given.
 */
export function normalizeKey(source: string): string {
  return source.replace(/\s+/g, ' ').trim()
}

export function createTranslator(locale: Locale): Translate {
  if (locale === defaultLocale) return (source) => source

  const dictionary = dictionaries[locale] ?? {}

  return (source) => {
    if (!source) return source
    const hit = dictionary[normalizeKey(source)]
    if (!hit) return source

    // Preserve whatever leading/trailing whitespace the caller had, since JSX
    // relies on it for spacing between inline elements.
    const [, lead = '', , trail = ''] = source.match(/^(\s*)([\s\S]*?)(\s*)$/) ?? []
    return `${lead}${hit}${trail}`
  }
}

/** Every source string we have an English translation for. */
export function knownSources(locale: Locale): string[] {
  return Object.keys(dictionaries[locale] ?? {})
}
